set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CROSS_TRIPLE aarch64-linux-gnu)
if (DEFINED GO2_AARCH64_CROSS_TRIPLE AND NOT GO2_AARCH64_CROSS_TRIPLE STREQUAL "")
  set(CROSS_TRIPLE ${GO2_AARCH64_CROSS_TRIPLE})
endif ()

if (DEFINED GO2_AARCH64_TOOLCHAIN_ROOT AND NOT GO2_AARCH64_TOOLCHAIN_ROOT STREQUAL "")
  set(CMAKE_C_COMPILER ${GO2_AARCH64_TOOLCHAIN_ROOT}/bin/${CROSS_TRIPLE}-gcc)
  set(CMAKE_CXX_COMPILER ${GO2_AARCH64_TOOLCHAIN_ROOT}/bin/${CROSS_TRIPLE}-g++)
else ()
  set(CMAKE_C_COMPILER ${CROSS_TRIPLE}-gcc)
  set(CMAKE_CXX_COMPILER ${CROSS_TRIPLE}-g++)
endif ()

if (NOT DEFINED GO2_AARCH64_SYSROOT OR GO2_AARCH64_SYSROOT STREQUAL "")
  if (DEFINED GO2_AARCH64_TOOLCHAIN_ROOT AND EXISTS "${GO2_AARCH64_TOOLCHAIN_ROOT}/${CROSS_TRIPLE}/libc")
    set(GO2_AARCH64_SYSROOT "${GO2_AARCH64_TOOLCHAIN_ROOT}/${CROSS_TRIPLE}/libc")
  endif ()
endif ()

# Optional external sysroot for Ubuntu 20.04 aarch64 runtime compatibility.
# Pass -DGO2_AARCH64_SYSROOT=/path/to/sysroot when available.
if (DEFINED GO2_AARCH64_SYSROOT AND NOT GO2_AARCH64_SYSROOT STREQUAL "")
  set(CMAKE_SYSROOT ${GO2_AARCH64_SYSROOT})
  set(CMAKE_FIND_ROOT_PATH ${GO2_AARCH64_SYSROOT})
  set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
  set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
  set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
  set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
endif ()

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
